version: "3"

# uffizzi integration
x-uffizzi:
  ingress:
    service: answer
    port: 8080

services:
  answer:
    image: "${ANSWER_IMAGE}"
    volumes:
      - answer-data:/data

volumes:
  answer-data:
