version: "3"

# uffizzi integration
x-uffizzi:
  ingress:
    service: answer
    port: 8081

services:
  answer:
    image: "${ANSWER_IMAGE}"
    volumes:
      - answer-data:/data
    deploy:
      resources:
        limits:
          memory: 2000M

volumes:
  answer-data:
