version: "3"

# uffizzi integration
x-uffizzi:
  ingress:
    service: answer
    port: 80

services:

  answer:
    image: "${ANSWER_IMAGE}"
    volumes:
      - answer-data:/data
    deploy:
      resources:
        limits:
          memory: 2000M

  postgres:
   image: postgres
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=postgres
   volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  answer-data:
  postgres_data:
